# Generated by Django 5.0 on 2023-12-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("noteapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note", name="content", field=models.TextField(blank=True),
        ),
    ]
